project_name: postee
release:
  draft: false
  prerelease: auto
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - make all
builds:
  - id: postee
    dir: .
    main: ./main.go
    binary: postee
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - postee
    replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .FullCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
dockers:
  - dockerfile: Dockerfile.release
    use: buildx
    image_templates:
      - "docker.io/aquasec/postee:{{ .Version }}"
      - "public.ecr.aws/aquasecurity/postee:{{ .Version }}"
      - "docker.io/aquasec/postee:latest"
      - "public.ecr.aws/aquasecurity/postee:latest"
    ids:
      - postee
    extra_files:
      - rego-templates/
      - rego-filters/
      - cfg.yaml
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Command line interface for Postee"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/postee"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - dockerfile: Dockerfile.ui
    use: buildx
    image_templates:
      - "docker.io/aquasec/postee-ui:{{ .Version }}"
      - "public.ecr.aws/aquasecurity/postee-ui:{{ .Version }}"
      - "docker.io/aquasec/postee-ui:latest"
      - "public.ecr.aws/aquasecurity/postee-ui:latest"
    ids:
      - postee-ui
    extra_files:
      - rego-templates/
      - rego-filters/
      - cfg.yaml
      - ui/
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Postee UI"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/postee"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
