FROM node:latest as vuebuilder
ADD ./ui/frontend /frontend
WORKDIR /frontend

RUN yarn install
RUN yarn build


FROM golang:1.16-alpine as gobuilder

ADD . /webhook
WORKDIR /webhook/ui/backend
RUN go build -o posteeui

FROM alpine
EXPOSE 8000

RUN mkdir /uiserver
RUN mkdir /uiserver/www

RUN mkdir /server
RUN mkdir /server/database

COPY --from=gobuilder /webhook/ui/backend/posteeui /uiserver
COPY --from=vuebuilder /frontend/dist /uiserver/www

WORKDIR /uiserver

ENTRYPOINT ["/uiserver/posteeui"]