FROM node:18-alpine3.17 as vuebuilder
COPY ./ui/frontend /frontend
WORKDIR /frontend

RUN yarn install
RUN yarn build


FROM golang:1.18-alpine as gobuilder

COPY . /server
WORKDIR /server/ui/backend
RUN apk add git
ARG TARGETOS TARGETARCH
RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build --ldflags "-s -w" -o posteeui

FROM alpine:3.18.3
EXPOSE 8001

RUN mkdir /uiserver
RUN mkdir /uiserver/www

RUN mkdir /server
RUN mkdir /server/database
RUN mkdir /config

COPY --from=gobuilder /server/ui/backend/posteeui /uiserver
COPY --from=vuebuilder /frontend/dist /uiserver/www

WORKDIR /uiserver
RUN addgroup -g 1099 postee
RUN adduser -D -g '' -G postee -u 1099 postee
RUN chown -R postee:postee /server
RUN chown -R postee:postee /config
RUN chown -R postee:postee /uiserver
USER postee
ENTRYPOINT ["/uiserver/posteeui"]
