FROM alpine:3.4
MAINTAINER admin@aquasec.com
RUN apk update && apk add wget ca-certificates

EXPOSE 8082
EXPOSE 8445

RUN mkdir -p /opt/scalock
COPY bin/webhooksrv /opt/scalock/
WORKDIR /opt/scalock/
CMD ["/opt/scalock/webhooksrv"]
