FROM node:alpine3.15 as vuebuilder
COPY ./ui/frontend /frontend
WORKDIR /frontend

RUN yarn install
RUN yarn build


FROM golang:1.18.1-alpine as gobuilder

COPY . /server
WORKDIR /server/ui/backend
RUN go build -o posteeui

FROM alpine:3.15
EXPOSE 8000

RUN mkdir /uiserver
RUN mkdir /uiserver/www

RUN mkdir /server
RUN mkdir /server/database
RUN mkdir /config

COPY --from=gobuilder /server/ui/backend/posteeui /uiserver
COPY --from=vuebuilder /frontend/dist /uiserver/www

WORKDIR /uiserver
RUN addgroup -g 1099 postee
RUN adduser -D -g '' -G postee -u 1099 postee
RUN chown -R postee:postee /server
RUN chown -R postee:postee /config
RUN chown -R postee:postee /uiserver
USER postee
ENTRYPOINT ["/uiserver/posteeui"]
