FROM alpine:latest
MAINTAINER admin@aquasec.com
RUN apk update && apk add wget ca-certificates

EXPOSE 8082
EXPOSE 8445

RUN mkdir -p /opt/aquasec
COPY bin/webhooksrv /opt/aquasec/
WORKDIR /opt/aquasec/
CMD ["/opt/aquasec/webhooksrv"]
