#Create the volume for the Postee volumeClaimTemplates
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postee-pv
  labels:
    app: postee-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/postee/