# The configuration file contains a general settings section,
# routes, templates and outputs sections.

name: tenant            #  The tenant name
aqua-server:            #  URL of Aqua Server for links. E.g. https://myserver.aquasec.com
max-db-size: 1000MB       #  Max size of DB. <numbers><unit suffix> pattern is used, such as "300MB" or "1GB". If empty or 0 then unlimited
db-verify-interval: 1   #  How often to check the DB size. By default, Postee checks every 1 hour

# Routes are used to define how to handle an incoming message
routes:
- name: stdout
  outputs: [ stdout ]
  template: raw-json

- name: actions-route
  input: contains(input.SigMetadata.ID, "TRC-2")
  outputs: [stop-vulnerable-pod]
  template: raw-json

# Templates are used to format a message
templates:
- name: raw-json                                   # route message "As Is" to external webhook
  rego-package: postee.rawmessage.json

# Outputs are target services that should consume the messages
outputs:
- name: stdout
  type: stdout
  enable: true

# Define a custom output of Docker action, that can take params.
- name: stop-vulnerable-pod
  type: docker
  enable: true
  docker-image-name: "bitnami/kubectl:latest"                          # Required. Image name of container to run.
  docker-cmd: ["delete", "pod", event.input.SigMetadata.hostname]      # Required. Command to run when starting container.
  docker-network: "host"                                               # Optional. Network name for docker container.
  docker-volume-mounts:                                                # Optional. Volume mounts present inside the container
    "path/to/.kube/config": "/.kube/config"