{{ if not .Values.configuration.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postee.fullname" . }}-secret
data:
  cfg.yaml: |
{{ .Values.posteeConfig  | b64enc | indent 4 }}
{{- end }}
