{{- if not .Values.posteUi.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postee.ui.fullname" . }}-creds
  labels:
    {{- include "postee.ui.labels" . | nindent 4 }}
type: Opaque
data:
  postee-ui-user: {{ .Values.posteUi.user | b64enc | quote }}
  postee-ui-password: {{ .Values.posteUi.pass | b64enc | quote }}
{{- end }}