---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aqua-postee
  name: postee-svc
spec:
  ports:
    - name: aqua-postee-ssl
      port: 8443
      protocol: TCP
      targetPort: 8445
    - name: aqua-postee
      port: 8080
      protocol: TCP
      targetPort: 8082
  selector:
    app: aqua-postee
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: aqua-postee
  name: postee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-postee
  serviceName: postee-svc
  volumeClaimTemplates:
    - metadata:
        name: postee-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: postee-config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
    - metadata:
        name: rego-template
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
  template:
    metadata:
      labels:
        app: aqua-postee
      name: aqua-postee
    spec:
      initContainers:
        - name: chmod-er
          image: busybox:latest
          command:
            - /bin/chown
            - -R
            - "1099"
            - /server/database
          volumeMounts:
            - name: postee-db
              mountPath: /server/database
        - name: init-cfg
          image: busybox:latest
          command:
            - cp
            - /data/cfg.yaml
            - /config/cfg.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /data
              readOnly: false
            - name: postee-config
              mountPath: /config
      containers:
        - image: aquasec/postee:latest
          imagePullPolicy: Always
          name: aqua-postee
          env:
            - name: POSTEE_CFG
              value: /config/cfg.yaml
            - name: POSTEE_DEBUG
              value: "not"
          ports:
            - containerPort: 8082
              protocol: TCP
            - containerPort: 8445
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /data
              readOnly: false
            - name: postee-db
              mountPath: /server/database
            - name: rego-template
              mountPath: /server/rego-template/custom
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: config-volume
          configMap:
            name: postee-config
            items:
            - key: cfg.yaml
              path: cfg.yaml
