---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: aqua-postee
  name: postee-svc
spec:
  ports:
    - name: aqua-postee-ssl
      port: 8443
      protocol: TCP
      targetPort: 8445
    - name: aqua-postee
      port: 8080
      protocol: TCP
      targetPort: 8082
  selector:
    app: aqua-postee
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: aqua-postee
  name: postee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-postee
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aqua-postee
      name: aqua-postee
    spec:
      initContainers:
        - name: chmod-er
          image: busybox:latest
          command:
            - /bin/chown
            - -R
            - "1099"  
            - /server/database
          volumeMounts:
            - name: postee-db
              mountPath: /server/database
      containers:
        - image: aquasec/postee:latest
          imagePullPolicy: Always
          name: aqua-postee
          env:
            - name: POSTEE_CFG
              value: /policy/cfg.yaml
            - name: POSTEE_DEBUG
              value: "not"
          ports:
            - containerPort: 8082
              protocol: TCP
            - containerPort: 8445
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /policy
            - name: rego-config
              mountPath: /rego
            - name: postee-db
              mountPath: /server/database
          livenessProbe:
            httpGet:
              path: /ping
              port: 8082
            initialDelaySeconds: 30
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
      volumes:
        - configMap:
            name: postee-config
          name: config-volume
        - configMap:
            name: rego-config
          name: rego-config
        - name: postee-db
          emptyDir: {} # For persistence storage use PVC and PV
