---
name: Go

on:
  push:
    branches: [postee-for-enterprise]
  pull_request:
    branches: [postee-for-enterprise]

jobs:

  buildEnterprise:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
        with:
          go-version: ^1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 # v2.5.2
        with:
          args: --verbose
          version: latest
      - name: check spell
        uses: codespell-project/actions-codespell@master
        with:
          skip: src,rego-templates,ui,go.mod,go.sum

      - name: Build
        run: make all

      - name: Test
        run: make test